## the list of groups for which motion planning can be performed
groups: 
  - arm

## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending 
## on the planner

arm:
  planner_type: JointPlanner
  projection_evaluator: joint_state
  planner_configs:
    - SBLkConfig1 
    - LBKPIECEkConfig1
#  ## --- kinematics plugin config following ---
#  kinematics_solver: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
#  tip_name: katana_gripper_tool_frame
#  root_name: katana_base_link

planner_configs:
  SBLkConfig1:
    type: kinematic::SBL
  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE

publish_diagnostics: true