default_robot_padding: 0.02
link_padding:
  - link: robot_body
    padding: 0.0
  - link: arm
    padding: 0.02
  - link: end_effector
    padding: 0.02
  - link: katana_l_finger_link 
    padding: 0.02
  - link: katana_r_finger_link 
    padding: 0.02
  - link: attached
    padding: 0.02
